#!/bin/bash
branch=`git rev-parse --abbrev-ref HEAD`
branchWithoutType=`echo "$branch" | cut -d'/' -f 2`
projectID=`echo "$branchWithoutType" | cut -d'-' -f 1` 
numberID=`echo "$branchWithoutType" | cut -d'-' -f 2`
ticketID="$projectID-$numberID"
git commit -m "$ticketID $1"
